# Generated by Django 3.1.4 on 2020-12-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201202_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_index',
            field=models.IntegerField(),
        ),
    ]
